# ===============================
# DATABASE CONFIG (SUPABASE POOLER - FINAL)
# ===============================
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.gupesksjdhebaonvtrfx
spring.datasource.password=&?L/5mL_!NdqMM7
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# HIKARI CONFIG
# ===============================
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=20000

# ===============================
# SERVER CONFIG
# ===============================
server.port=8080
allowed.origins=http://localhost:5173,http://localhost:5174

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=SFourTradersSecretKey2024VeryLongStringForSecurity123456
jwt.expiration=86400000

# ===============================
# DEFAULT LOGIN
# ===============================
app.username=admin
app.password=sfour2024